In [1]:
import numpy as np


In [2]:
"""
Numpy Array Attributes
"""

# Creating an array

print(np.arange(3))
print(np.arange(3, 9))
print(np.arange(3, 9, 2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [3]:
np.random.seed(0)
arr1 = np.random.randint(10, size = (3, 4, 5))
print(arr1)


[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]


In [4]:
# Attributes
np.random.seed(1)
arr = np.random.randint(10, size = (3,4))
print(arr)

print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)
print("arr.size = ", arr.size)

print("arr.dtype = ", arr.dtype)
print("arr.itemsize = ", arr.itemsize)
print("arr.nbytes = ", arr.nbytes) 

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
arr.ndim =  2
arr.shape =  (3, 4)
arr.size =  12
arr.dtype =  int32
arr.itemsize =  4
arr.nbytes =  48


In [5]:
"""
Subarrays as np-copy views
"""

np.random.seed(3)
arr = np.random.randint(10, size = (6, 8))
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]
[[8 9]
 [9 9]]
[[99  9]
 [ 9  9]]
[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]


In [6]:
"""
Array Concatenation
"""

# np.concatenate(), np.vstack(), np.hstack()

arr_1 = np.array([[1, 2, 3], [1, 2, 3]])
arr_2 = np.array([[4, 5, 6], [4, 5, 6]])
arr_3 = np.array([[7, 8, 9], [7, 8, 9]])

arr_total = np.concatenate([arr_1, arr_2, arr_3], axis = 1)
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)


[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
